import Link from "next/link";
import Navbar from "@/components/Navbar";

const steps = [
  {
    title: "1. Collect Market Intelligence",
    description:
      "The Intelligence Engine continuously monitors multiple market dimensions and transforms raw data into machine-readable intelligence.",
    items: [
      "Market structure",
      "Price action",
      "Volatility",
      "Liquidity conditions",
      "Narrative shifts",
    ],
    output: "Market Intelligence Score",
  },
  {
    title: "2. Generate Trading Signal",
    description:
      "AI agents evaluate market conditions and produce directional signals.",
    items: ["Trend direction", "Confidence level", "Risk profile"],
    output: "LONG • SHORT • NEUTRAL",
  },
  {
    title: "3. Explainable Decision Layer",
    description:
      "Every decision generated by the system is transparent and explainable.",
    items: ["Reasons", "Confidence breakdown", "Risk notes", "Agent consensus"],
  },
  {
    title: "4. Risk Validation",
    description: "Before execution, multiple safety checks are performed.",
    items: [
      "Signal confidence > threshold",
      "Risk score < threshold",
      "Liquidity available",
      "Wallet connected",
    ],
  },
  {
    title: "5. Execute Trade",
    description:
      "The Execution Engine manages transaction creation and confirmation.",
    items: [
      "Build transaction",
      "Broadcast to Solana",
      "Wait confirmation",
      "Store proof hash",
    ],
  },
  {
    title: "6. Generate Execution Proof",
    description:
      "Every execution creates an auditable record for transparency.",
    items: [
      "Proof Hash",
      "Transaction Signature",
      "Timestamp",
      "Execution Metadata",
    ],
    output: "Immutable Execution Trail",
  },
];

export default function HowPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      <Navbar />

      {/* HERO */}
      <section className="max-w-7xl mx-auto px-6 py-24 text-center">
        <div className="inline-flex items-center rounded-full border border-[#1A1A1A] px-4 py-2 text-xs text-[#7A7A7A]">
          SHADOWALPHA DOCUMENTATION
        </div>

        <h1 className="mt-8 text-5xl md:text-6xl font-bold">
          How ShadowAlpha Works
        </h1>

        <p className="max-w-3xl mx-auto mt-6 text-[#7A7A7A] text-lg">
          ShadowAlpha transforms raw market data into autonomous execution
          through a multi-agent architecture that combines intelligence,
          decision-making, risk management, execution, and proof generation.
        </p>

        <div className="mt-12 flex flex-col items-center gap-3 text-sm">
          <div>Market Data</div>
          <div className="text-[#FF6B00]">↓</div>

          <div>Intelligence Engine</div>
          <div className="text-[#FF6B00]">↓</div>

          <div>Decision Layer</div>
          <div className="text-[#FF6B00]">↓</div>

          <div>Risk Engine</div>
          <div className="text-[#FF6B00]">↓</div>

          <div>Execution Engine</div>
          <div className="text-[#FF6B00]">↓</div>

          <div>Onchain Proof</div>
        </div>
      </section>

      {/* EXECUTION LIFECYCLE */}
      <section className="border-t border-[#1A1A1A]">
        <div className="max-w-7xl mx-auto px-6 py-24">
          <h2 className="text-4xl font-bold text-center">
            Execution Lifecycle
          </h2>

          <div className="grid md:grid-cols-2 gap-8 mt-16">
            {steps.map((step) => (
              <div
                key={step.title}
                className="
                  rounded-3xl
                  border border-[#1A1A1A]
                  bg-[#0D0D0D]
                  p-6
                "
              >
                <h3 className="text-xl font-semibold">{step.title}</h3>

                <p className="mt-3 text-[#7A7A7A]">{step.description}</p>

                <ul className="mt-5 space-y-2 text-sm">
                  {step.items.map((item) => (
                    <li key={item} className="text-[#CCCCCC]">
                      • {item}
                    </li>
                  ))}
                </ul>

                {step.output && (
                  <div className="mt-5 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-3">
                    <div className="text-xs text-cyan-400">OUTPUT</div>

                    <div className="mt-1 text-sm">{step.output}</div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SYSTEM ARCHITECTURE */}
      <section className="border-t border-[#1A1A1A]">
        <div className="max-w-5xl mx-auto px-6 py-24">
          <h2 className="text-4xl font-bold text-center">
            System Architecture
          </h2>

          <div className="mt-16 flex flex-col items-center">
            {[
              "Market Data",
              "Intelligence AI",
              "Decision Layer",
              "Risk Engine",
              "Execution Layer",
              "Proof System",
            ].map((item, index) => (
              <div key={item} className="flex flex-col items-center">
                <div
                  className="
                    w-72
                    rounded-2xl
                    border border-[#1A1A1A]
                    bg-[#0D0D0D]
                    p-5
                    text-center
                    font-medium
                  "
                >
                  {item}
                </div>

                {index !== 5 && (
                  <div className="py-3 text-[#FF6B00] text-xl">↓</div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* WHY IT MATTERS */}
      <section className="border-t border-[#1A1A1A]">
        <div className="max-w-7xl mx-auto px-6 py-24">
          <h2 className="text-4xl font-bold text-center">Why It Matters</h2>

          <div className="grid md:grid-cols-3 gap-8 mt-16">
            <div className="rounded-3xl border border-[#1A1A1A] bg-[#0D0D0D] p-6">
              <h3 className="text-xl font-semibold">Explainable Decisions</h3>

              <p className="mt-3 text-[#7A7A7A]">
                Every trade includes reasoning, confidence metrics, and risk
                context.
              </p>
            </div>

            <div className="rounded-3xl border border-[#1A1A1A] bg-[#0D0D0D] p-6">
              <h3 className="text-xl font-semibold">Autonomous Execution</h3>

              <p className="mt-3 text-[#7A7A7A]">
                Signals can flow directly into execution logic without manual
                intervention.
              </p>
            </div>

            <div className="rounded-3xl border border-[#1A1A1A] bg-[#0D0D0D] p-6">
              <h3 className="text-xl font-semibold">Auditable Proof Layer</h3>

              <p className="mt-3 text-[#7A7A7A]">
                Every execution produces a verifiable proof trail.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-[#1A1A1A]">
        <div className="max-w-4xl mx-auto px-6 py-24 text-center">
          <h2 className="text-4xl font-bold">
            Ready to Explore the Execution Layer?
          </h2>

          <p className="mt-4 text-[#7A7A7A]">
            Access the ShadowAlpha terminal and observe the complete
            intelligence-to-execution workflow.
          </p>

          <Link
            href="/terminal"
            className="
              inline-block
              mt-8
              rounded-2xl
              bg-[#FF6B00]
              px-8
              py-4
              font-medium
            "
          >
            Open Terminal
          </Link>
        </div>
      </section>
    </main>
  );
}
